### ISSUE TITLE
OAuth - Authentication fails

### ISSUE THREAD

**Issue by Lusyok** [twilio/stashboard#22] opened 2011-09-06 11:15 UTC
After deploying application to Google , I was able to get API Credentials. 

Customer Name - anonymous , OAuthToken  -xxxxxxxxxx OAuthSecret - yyyyyyyyy.

I was able to add services via interface, but POST requests via API always fail. 

I have tried Python and PHP samples, and also other java lib for OAuth , no success.  

Here is what I get as a response: Response: 403  errore {"message": "Authorization Failure", "code": 403, "error": true}.

Will much appreciate any help.

**Comment by kyleconroy** [comment] 2011-09-07 17:21
@Lusyok, what version of Stashboard are you using?

**Comment by Lusyok** [comment] 2011-09-08 04:22
I am using version twilio-stashboard-1.1.6-6-g5a66ba6 . Let me know if you need any other information. Thanks for help.

**Comment by pburkholder** [comment] 2012-10-31 12:56
Hello.  Similar problem here, Kyle.  Any tips?  I'm using GitHub master HEAD.

**Comment by kyleconroy** [comment] 2012-11-07 22:46
Closing as a duplicate of Issue #9

**Closed as completed by kyleconroy** 2012-11-07 22:46 UTC
